---
- name: Update repository
  apt: update_cache=true
  become: yes

- name: Install Nginx
  apt: name={{ variable }} state=present update_cache=true

- name: Create web directory
  file: path=/var/www/html mode=775 state=directory

- name: Copy nginx configuration 
  template: src=nginx.conf dest=/etc/nginx/conf.d/default.conf

- name: Copy index.html 
  template: src=index.html dest=/var/www/html/index.html